# Generated by Django 5.1.4 on 2025-01-18 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Highway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('police', 'Police'), ('ambulance', 'Ambulance'), ('fire', 'Fire Department')], max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('highway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='autouroute_api.highway')),
            ],
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_type', models.CharField(choices=[('collision', 'Collision'), ('rollover', 'Rollover'), ('pedestrian', 'Pedestrian Accident'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('fatal', 'Fatal')], max_length=50)),
                ('description', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('emergency_contact_called', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved')], default='reported', max_length=50)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('highway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='autouroute_api.highway')),
            ],
        ),
        migrations.CreateModel(
            name='HighwayStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_construction', 'Under Construction'), ('closed', 'Closed')], max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('highway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='autouroute_api.highway')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('has_gas_station', models.BooleanField(default=False)),
                ('has_restaurant', models.BooleanField(default=False)),
                ('has_bathroom', models.BooleanField(default=False)),
                ('highway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_areas', to='autouroute_api.highway')),
            ],
        ),
        migrations.CreateModel(
            name='Toll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('vehicle_category', models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle')], max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('highway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolls', to='autouroute_api.highway')),
            ],
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('density', models.CharField(choices=[('light', 'Light'), ('moderate', 'Moderate'), ('heavy', 'Heavy')], max_length=50)),
                ('average_speed', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('highway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_updates', to='autouroute_api.highway')),
            ],
        ),
    ]
