# Generated by Django 5.1.4 on 2025-01-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autouroute_api', '0002_highway_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='toll',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
