# Generated by Django 5.1.4 on 2025-01-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autouroute_api', '0003_toll_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='toll',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
