# Generated by Django 5.1.4 on 2025-01-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autouroute_api', '0005_toll_created_at_toll_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Traffic',
        ),
    ]
